name: 01.build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core SDK 6.0
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: 6.0.x
      - name: Resotre
        run: dotnet restore src/*.sln
      - name: Build
        run: dotnet build src/*.sln --configuration Release --no-restore
      - name: UnitTest
        run: dotnet test src/SimpleWeb.UnitTest/SimpleWeb.UnitTest.csproj --no-restore --verbosity normal
      - name: IntegrationTest
        run: dotnet test src/SimpleWeb.IntegrationTest/SimpleWeb.IntegrationTest.csproj --no-restore --verbosity normal
