name: 01.build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET SDK 10.0
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x
      - name: Restore
        run: dotnet restore src/*.sln
      - name: Build
        run: dotnet build src/*.sln --configuration Release --no-restore
      - name: UnitTest
        run: dotnet test src/SimpleWeb.UnitTest/SimpleWeb.UnitTest.csproj --no-restore --verbosity normal
      - name: IntegrationTest
        run: dotnet test src/SimpleWeb.IntegrationTest/SimpleWeb.IntegrationTest.csproj --no-restore --verbosity normal
