name: 01.prwithlimitbranch

on:
  pull_request:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: read

env:
  buildConfiguration: 'Release'
  targetBranch: 'dev'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Show variables
        env:
          GITHUB_HEAD_REF: ${{ github.head_ref }}
          GITHUB_BASE_REF: ${{ github.base_ref }}
          GITHUB_REF: ${{ github.ref }}
        run: |
          echo "GitHub Ref: $GITHUB_REF"
          echo "GitHub Head Ref: $GITHUB_HEAD_REF"
          echo "GitHub Base Ref: $GITHUB_BASE_REF"

      - name: Check target branch
        if: github.head_ref != env.targetBranch
        env:
          GITHUB_HEAD_REF: ${{ github.head_ref }}
        run: |
          echo "Info: Pull requests to master must originate from the dev branch. Current source branch: $GITHUB_HEAD_REF"
          exit 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x

      - name: Restore
        run: dotnet restore src/*.sln

      - name: Build
        run: dotnet build src/*.sln --configuration ${{ env.buildConfiguration }} --no-restore

      - name: UnitTest
        run: dotnet test src/SimpleWeb.UnitTest/SimpleWeb.UnitTest.csproj --no-restore --verbosity normal
